# Generated by Django 4.2.11 on 2025-01-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
